export const cars = [
    {
        id: 1,
        brand: 'BMW',
        model: 'X5',
        type: 'SUV',
        price: 2500,
        image: './images/bmwX5/bmwX5_list.jpg',
        main_img: './images/bmwX5/bmwX5_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/bmwX5/bmwX5_img1.jpg',
        img2: './images/bmwX5/bmwX5_img2.jpg',
        general: 'The 2025 BMW X5 boasts a classy-looking cabin, plenty of upscale features and pleasing performance. A variety of engines are also available to appeal to the power-hungry and fuel-conscious alike. Overall, the X5 is one of the most appealing midsize luxury SUVs on the market.'
    },
    {
        id: 2,
        brand: 'Toyota',
        model: 'Corolla',
        type: 'Sedan',
        price: 700,
        image: './images/toyotaCorolla/toyotaCorolla_list.jpg',
        main_img: './images/toyotaCorolla/toyotaCorolla_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/toyotaCorolla/toyotaCorolla_img1.jpg',
        img2: './images/toyotaCorolla/toyotaCorolla_img2.jpg',
        general: 'The Toyota Corolla is known for its reliability, fuel efficiency, and smooth ride, making it a popular choice for daily commuters and families alike.'
    },
    {
        id: 3,
        brand: 'Ford',
        model: 'F-150',
        type: 'Truck',
        price: 1000,
        image: './images/fordTruck/fordTruck_list.jpg',
        main_img: './images/fordTruck/fordTruck_details.jpg',
        available: false,
        doors: 4,
        capacity: '5-6 passengers',
        transmission: 'Automatic',
        luggage: '3 Large Suitcases, 2 Small Bags (in truck bed)',
        air_condition: 'yes',
        age: 25,
        img1: './images/fordTruck/fordTruck_img1.jpg',
        img2: './images/fordTruck/fordTruck_img2.jpg',
        general: "The beauty of the 2025 Ford F-150 Lightning electric pickup is that, at its core, it's an F-150. That means it retains the goodness of Ford's best-selling pickup, with a comfortable interior, rugged construction, and plenty of high-tech features. It also has good range on a full charge and is impressively quick. Just note that its tow rating isn't as robust as the capabilities of gas-powered F-150s, and its range drops dramatically when pulling a trailer."
    },
    {
        id: 4,
        brand: 'Kia',
        model: 'Sportage',
        type: 'SUV',
        price: 2000,
        image: './images/kiaSportage/kiaSportage_list.jpg',
        main_img: './images/kiaSportage/kiaSportage_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/kiaSportage/kiaSportage_img1.jpg',
        img2: './images/kiaSportage/kiaSportage_img2.jpg',
        general: "With the Sportage, Kia offers a scaled approach to electrification. A traditional internal combustion engine powers the most affordable versions of the small SUV, and a regular hybrid is a small upcharge. The plug-in hybrid is significantly more expensive than the other versions of the Sportage, though it does include standard all-wheel drive. Not only does the plug-in have a 35-mile electric range, but it's also appreciably more powerful and quicker than the other Sportages."
    },
    {
        id: 5,
        brand: 'Jeep',
        model: 'Grand Cherokee',
        type: 'SUV',
        price: 3500,
        image: './images/jeepGrandCherokee/jeep_list.jpg',
        main_img: './images/jeepGrandCherokee/jeep_details.jpg',
        available: false,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 or 3 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/jeepGrandCherokee/jeep_img1.jpg',
        img2: './images/jeepGrandCherokee/jeep_img2.jpg',
        general: "The Jeep Grand Cherokee combines rugged off-road capability with a comfortable interior and modern technology. It's ideal for outdoor adventures and long drives."
    },
    {
        id: 6,
        brand: 'Mercedes-Benz',
        model: 'GLC-Class',
        type: 'Sedan',
        price: 1800,
        image: './images/mercedesBenzC-class/mercedesC-class_list.jpg',
        main_img: './images/mercedesBenzC-class/mercedesC-class_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1 or 2 Large Suitcases, 1 or 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/mercedesBenzC-class/mercedesC-class_img1.jpg',
        img2: './images/mercedesBenzC-class/mercedesC-class_img2.jpg',
        general: "The Mercedes-Benz GLC is the German luxury carmaker's small SUV and best-selling vehicle. The GLC Coupe version features a sloping coupe-inspired rear roofline that gives it a sleeker silhouette in exchange for slightly reduced rear seat headroom and cargo capacity."
    },
    {
        id: 7,
        brand: 'Lamborghini',
        model: 'Huracan',
        type: 'Sport',
        price: 5000,
        image: './images/LamborghiHuracan/Lamborghini_list.jpg',
        main_img: './images/LamborghiHuracan/Lamborghini_details.jpg',
        available: true,
        doors: 2,
        capacity: '2 passengers',
        transmission: 'Automatic (Dual-clutch)',
        luggage: '1 Small bag (front trunk)',
        air_condition: 'yes',
        age: 25,
        img1: './images/LamborghiHuracan/Lamborghini_img1.jpg',
        img2: './images/LamborghiHuracan/Lamborghini_img2.jpg',
        general: "The Lamborghini Huracan impresses with its remarkable capability. The car delivers commendable power, excellent reflexes, endless grip, and fantastic braking competence. This is Lamborghini at its sports car finest."
    },
    {
        id: 8,
        brand: 'Ferrari',
        model: '488 Pista',
        type: 'Sport',
        price: 6500,
        image: './images/FerrariPista/ferrariPista_list.jpg',
        main_img: './images/FerrariPista/ferrariPista_details.jpg',
        available: true,
        doors: 2,
        capacity: '2 passengers',
        transmission: 'Automatic (Dual-clutch)',
        luggage: '1 Small bag (front trunk)',
        air_condition: 'yes',
        age: 25,
        img1: './images/FerrariPista/ferrariPista_img1.jpg',
        img2: './images/FerrariPista/ferrariPista_img2.jpg',
        general: "The Ferrari 488 Pista is powered by the most powerful V8 engine in the Maranello marque’s history and is the company’s special series sports car with the highest level of technological transfer from racing."
    },
    {
        id: 9,
        brand: 'Rolls Royce',
        model: 'Phantom',
        type: 'Luxury',
        price: 8800,
        image: './images/rollsRoycePhantom/rollsRoyce_list.jpg',
        main_img: './images/rollsRoycePhantom/rollsRoyce_details.jpg',
        available: false,
        doors: 4,
        capacity: '4-5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/rollsRoycePhantom/rollsRoyce_img1.jpg',
        img2: './images/rollsRoycePhantom/rollsRoyce_img2.jpg',
        general: "The Rolls-Royce Phantom is one of the most exclusive cars in the world, offering unparalleled customization and luxury for the most discerning clientele."
    },
    {
        id: 10,
        brand: 'Mini',
        model: 'Cooper',
        type: 'Hatchback',
        price: 1600,
        image: './images/miniCooperHatchback/miniCooper_list.png',
        main_img: './images/miniCooperHatchback/miniCooper_details.jpg',
        available: true,
        doors: 2,
        capacity: '4 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase',
        air_condition: 'yes',
        age: 25,
        img1: './images/miniCooperHatchback/miniCooper_img1.jpg',
        img2: './images/miniCooperHatchback/miniCooper_img2.jpg',
        general: 'The Mini Cooper Hatchback blends iconic design with sporty performance, offering a unique driving experience in a compact size.'
    },
    {
        id: 11,
        brand: 'Mazda',
        model: 'CX-5',
        type: 'SUV',
        price: 1500,
        image: './images/mazdaCX5/mazdaCX5_list.jpg',
        main_img:'./images/mazdaCX5/mazdaCX5_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/mazdaCX5/mazdaCX5_img1.jpg',
        img2: './images/mazdaCX5/mazdaCX5_img2.jpg',
        general: "The Mazda CX-5 is a compact crossover SUV that offers a premium-feeling interior, responsive handling, and a strong value proposition. It's known for its stylish design and smooth driving experience."
    },
    {
        id: 12,
        brand: 'Honda',
        model: 'Civic',
        type: 'Sedan',
        price: 800,
        image: './images/hondaCivic/hondaCivic_list.jpg',
        main_img: './images/hondaCivic/hondaCivic_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/hondaCivic/hondaCivic_img1.jpg',
        img2: './images/hondaCivic/hondaCivic_img2.jpg',
        general: "The Honda Civic is a popular compact car that offers impressive fuel economy, a comfortable ride, and a reputation for reliability. It’s a great option for those seeking a practical and affordable vehicle."
    },
    {
        id: 13,
        brand: 'Porsche',
        model: '911 Carrera',
        type: 'Sport',
        price: 7000,
        image: './images/porscheCarrera/porsche_list.jpg',
        main_img: './images/porscheCarrera/porsche_details.jpg',
        available: true,
        doors: 2,
        capacity: '2 passengers',
        transmission: 'Automatic (Dual-clutch)',
        luggage: '1 Small bag (front trunk)',
        air_condition: 'yes',
        age: 25,
        img1: './images/porscheCarrera/porsche_img1.jpg',
        img2: './images/porscheCarrera/porsche_img2.jpg',
        general: "The Porsche 911 Carrera is a legendary sports car, delivering a thrilling driving experience with its iconic design, exceptional performance, and cutting-edge technology."
    },
    {
        id: 14,
        brand: 'Chevrolet',
        model: 'Traverse',
        type: 'SUV',
        price: 2300,
        image: './images/chevroletTraverse/chevroletTraverse_list.jpg',
        main_img: './images/chevroletTraverse/chevroletTraverse_details.jpg',
        available: true,
        doors: 4,
        capacity: '7 passengers',
        transmission: 'Automatic',
        luggage: '3 Large Suitcases, 3 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/chevroletTraverse/chevroletTraverse_img1.jpg',
        img2: './images/chevroletTraverse/chevroletTraverse_img2.jpg',
        general: "The Chevrolet Traverse is a large three-row SUV that offers spacious seating for up to 8 passengers, making it ideal for family road trips and group outings."
    },
    {
        id: 15,
        brand: 'Land Rover',
        model: 'Discovery',
        type: 'SUV',
        price: 3800,
        image: './images/landRoverDiscovery/landRover_list.jpg',
        main_img: './images/landRoverDiscovery/landRover_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/landRoverDiscovery/landRover_img1.jpg',
        img2: './images/landRoverDiscovery/landRover_img2.jpg',
        general: "The Land Rover Discovery is a luxury SUV designed for both off-road capability and on-road comfort. It’s known for its robust construction and high-end features."
    },
    {
        id: 16,
        brand: 'BMW',
        model: 'M5',
        type: 'Sport',
        price: 5000,
        image: './images/bmwM5/bmwM5_list.jpg',
        main_img: './images/bmwM5/bmwM5_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/bmwM5/bmwM5_img1.jpg',
        img2: './images/bmwM5/bmwM5_img2.jpg',
        general: "The BMW M5 is a high-performance sedan that delivers explosive power, remarkable handling, and a sophisticated interior, making it one of the ultimate luxury sports sedans."
    },
    {
        id: 17,
        brand: 'Fiat',
        model: '500',
        type: 'Hatchback',
        price: 900,
        image: './images/fiat500/fiat500_list.jpg',
        main_img: './images/fiat500/fiat500_details.jpg',
        available: true,
        doors: 2,
        capacity: '4 passengers',
        transmission: 'Automatic',
        luggage: '1 Small Bag',
        air_condition: 'yes',
        age: 25,
        img1: './images/fiat500/fiat500_img1.jpg',
        img2: './images/fiat500/fiat500_img2.jpg',
        general: 'The Fiat 500 is a charming city car with retro styling, compact dimensions, and nimble handling, ideal for urban environments.'
    },
    {
        id: 18,
        brand: 'Mercedes-Benz',
        model: 'C-Class Cabriolet',
        type: 'Convertible',
        price: 4000,
        image: './images/mercedesBenzCabriolet/mercedesBenz_list.jpg',
        main_img: './images/mercedesBenzCabriolet/mercedesBenz_details.jpg',
        available: true,
        doors: 2,
        capacity: '4 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 1 Small Bag',
        air_condition: 'yes',
        age: 25,
        img1: './images/mercedesBenzCabriolet/mercedesBenz_img1.jpg',
        img2: './images/mercedesBenzCabriolet/mercedesBenz_img2.jpg',
        general: 'The Mercedes-Benz C-Class Cabriolet blends luxury and sportiness with a high-quality cabin and smooth open-air driving.'
    },
    {
        id: 19,
        brand: 'Audi',
        model: 'A3 Cabriolet',
        type: 'Convertible',
        price: 3200,
        image: './images/audiA3/audiA3_list.jpg',
        main_img: './images/audiA3/audiA3_details.jpg',
        available: true,
        doors: 2,
        capacity: '4 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 1 Small Bag',
        air_condition: 'yes',
        age: 25,
        img1: './images/audiA3/audiA3_img1.jpg',
        img2: './images/audiA3/audiA3_img2.jpg',
        general: 'The Audi A3 Cabriolet offers stylish open-top motoring with a premium interior, advanced tech, and smooth driving dynamics.'
    },
    {
        id: 20,
        brand: 'Toyota',
        model: 'Highlander',
        type: 'SUV',
        price: 2900,
        image: './images/toyotaHighlander/toyotaHighlander_list.jpg',
        main_img: './images/toyotaHighlander/toyotaHighlander_details.jpg',
        available: true,
        doors: 4,
        capacity: '7 passengers',
        transmission: 'Automatic',
        luggage: '3 Large Suitcases, 3 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/toyotaHighlander/toyotaHighlander_img1.jpg',
        img2: './images/toyotaHighlander/toyotaHighlander_img2.jpg',
        general: "The Toyota Highlander is a mid-size SUV that provides a comfortable ride, a spacious interior, and an impressive list of features, making it a great option for families."
    },
    {
        id: 21,
        brand: 'Jaguar',
        model: 'F-Pace',
        type: 'SUV',
        price: 4200,
        image: './images/jaguarF-Pace/jaguarF-Pace_list.jpg',
        main_img: './images/jaguarF-Pace/jaguarF-Pace_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '2 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/jaguarF-Pace/jaguarF-Pace_img1.jpg',
        img2: './images/jaguarF-Pace/jaguarF-Pace_img2.jpg',
        general: "The Jaguar F-Pace offers luxury, performance, and an engaging driving experience. It’s a high-performance SUV that excels in both on-road comfort and off-road capability."
    },
    {
        id: 22,
        brand: 'Suzuki',
        model: 'Swift',
        type: 'Hatchback',
        price: 1700,
        image: './images/suzukiSwift/suzukiSwift_list.jpg',
        main_img: './images/suzukiSwift/suzukiSwift_details.jpg',
        available: true,
        doors: 5,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 1 Small Bag',
        air_condition: 'yes',
        age: 25,
        img1:'./images/suzukiSwift/suzukiSwift_img1.jpg',
        img2:'./images/suzukiSwift/suzukiSwift_img2.jpg',
        general:"Suzuki Swift is one of the most popular vehicles in not just its own segment, but the Indian car market in general. The hatchback offers an extremely fuel-efficient engine, decent interior space, and handsome looks, all at an extremely affordable price. The vehicle also has great driving dynamics, which makes it extremely fun to drive."
    },
    {
        id: 23,
        brand: 'Mazda',
        model: 'MX-5',
        type: 'Convertible',
        price: 7500,
        image: './images/mazdaX5/mazdaX5_list.jpg',
        main_img: './images/mazdaX5/mazdaX5_details.jpg',
        available: true,
        doors: 2,
        capacity: '2 passengers',
        transmission: '(Manual & Automatic) both Available',
        luggage: '1 Small bag',
        air_condition: 'yes',
        age: 25,
        img1:'./images/mazdaX5/mazdaX5_img1.jpg',
        img2:'./images/mazdaX5/mazdaX5_img2.jpg',
        general: "The Mazda MX-5 is a lightweight two-seater convertible, known for its sporty handling and fun-to-drive character. It offers both manual and automatic transmissions, making it perfect for driving enthusiasts who enjoy open-air motoring."
    },
    {
        id: 24,
        brand: 'BMW',
        model: '4 Series',
        type: 'Convertible',
        price: 9200,
        image: './images/bmw4series/bmw4series_list.jpg',
        main_img: './images/bmw4series/bmw4series_details.jpg',
        available: false,
        doors: 2,
        capacity: '4 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 1 Small Bag',
        air_condition: 'yes',
        age: 23,
        img1:'./images/bmw4series/bmw4series_img1.jpg',
        img2:'./images/bmw4series/bmw4series_img2.jpg',
        general: "The BMW 4 Series Convertible is a luxury sports car with two doors and a retractable roof, designed for open-top driving enthusiasts, offering powerful performance and a sleek, premium design."
    },
    {
        id: 25,
        brand: 'Hyundai',
        model: 'Elantra',
        type: 'Sedan',
        price: 2300,
        image: './images/hyundaiElantra/hyundaiElantra_list.jpg',
        main_img: './images/hyundaiElantra/hyundaiElantra_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1-2 Large Suitcase, 1 Small Bag',
        air_condition: 'yes',
        age: 24,
        img1:'./images/hyundaiElantra/hyundaiElantra_img1.jpg',
        img2:'./images/hyundaiElantra/hyundaiElantra_img2.jpg',
        general: "The Hyundai Elantra is a practical and economical sedan featuring a spacious interior and modern technology, ideal for daily use with comfortable driving and great fuel efficiency."
    },
    {
        id: 26,
        brand: 'Honda',
        model: 'Odyssey',
        type: 'Minivan',
        price: 6800,
        image: './images/hondaOdyssey/hondaOdyssey_list.jpg',
        main_img: './images/hondaOdyssey/hondaOdyssey_details.jpg',
        available: true,
        doors: 5,
        capacity: '7-8 passengers',
        transmission: 'Automatic',
        luggage: '3-4 Large Suitcases, 2 Small Bags',
        air_condition: 'yes',
        age: 26,
        img1: './images/hondaOdyssey/hondaOdyssey_img1.jpg',
        img2: './images/hondaOdyssey/hondaOdyssey_img2.jpg',
        general: "The Honda Odyssey is a comfortable and spacious minivan designed for families and group travel. It offers flexible seating for 7 to 8 passengers, a smooth automatic transmission, and ample luggage space, making it perfect for long trips and daily use."
    },    
    {
        id: 27,
        brand: 'Audi',
        model: 'A3',
        type: 'Hatchback',
        price: 4350,
        image: './images/audiA3Hatchback/audiA3Hatchback_list.jpg',
        main_img: './images/audiA3Hatchback/audiA3Hatchback_details.jpg',
        available: false,
        doors: 5,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1-2 Large Suitcase, 1-2 Small Bag',
        air_condition: 'yes',
        age: 22,
        img1:'./images/audiA3Hatchback/audiA3Hatchback_img1.jpg',
        img2:'./images/audiA3Hatchback/audiA3Hatchback_img2.jpg',
        general:"A masterclass in how to put premium gloss on a humble hatchback, the latest Audi A3 Sportback combines angular and aggressive new styling with a swanky cabin bristling with the latest technology. The foundations beneath play it a little safer but Audi knows its customers and the style and content are enough to make it a desirable alternative to the equivalent BMW 1 Series and Mercedes-Benz A-Class."
    },
    {
        id: 28,
        brand: 'Kia',
        model: 'Carnival',
        type: 'Minivan',
        price: 5000,
        image: './images/kiaCarnival/kiaCarnival_list.jpg',
        main_img: './images/kiaCarnival/kiaCarnival_details.jpg',
        available: true,
        doors: '5',
        capacity: '7–8 passengers',
        transmission: 'Automatic',
        luggage: '3 Large, 2–3 Small',
        air_condition: 'yes (multi-zone)',
        age: 25,
        img1: './images/kiaCarnival/kiaCarnival_img1.jpg',
        img2: './images/kiaCarnival/kiaCarnival_img2.jpg',
        general: "The Kia Carnival is a family-focused minivan offering premium comfort, a spacious cabin, and advanced convenience features, perfect for group travel."
    },
    {
        id: 29,
        brand: 'Volkswagen',
        model: 'Golf',
        type: 'Hatchback',
        price: 1400,
        image: './images/volkswagenGolf/volkswagenGolf_list.jpg',
        main_img: './images/volkswagenGolf/volkswagenGolf_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '1 Large Suitcase, 2 Small Bags',
        air_condition: 'yes',
        age: 25,
        img1: './images/volkswagenGolf/volkswagenGolf_img1.jpg',
        img2: './images/volkswagenGolf/volkswagenGolf_img2.jpg',
        general: 'The Volkswagen Golf is a compact hatchback known for its sporty handling, refined interior, and advanced safety features. It’s a favorite in the compact car segment.'
    },
    {
        id: 30,
        brand: 'Rolls-Royce',
        model: 'Cullinan',
        type: 'Luxury',
        price: 25000,
        image: './images/rollsRoyceCullinan/rollsRoyceCullinan_list.jpg',
        main_img: './images/rollsRoyceCullinan/rollsRoyceCullinan_details.jpg',
        available: true,
        doors: 4,
        capacity: '4–5 passengers',
        transmission: 'Automatic',
        luggage: '3 Large, 2 Small',
        air_condition: 'yes (luxury multi-zone)',
        age: 30,
        img1: './images/rollsRoyceCullinan/rollsRoyceCullinan_img1.jpg',
        img2: './images/rollsRoyceCullinan/rollsRoyceCullinan_img2.jpg',
        general: "The Rolls-Royce Cullinan is the pinnacle of SUV luxury, combining opulent comfort with a commanding presence and unparalleled craftsmanship."
    },
    {
        id: 31,
        brand: 'Range Rover',
        model: 'Autobiography',
        type: 'Luxury',
        price: 12000,
        image: './images/rangeRover/rangeRover_list.jpg',
        main_img: './images/rangeRover/rangeRover_details.jpg',
        available: true,
        doors: 4,
        capacity: '5 passengers',
        transmission: 'Automatic',
        luggage: '3 Large, 2 Small',
        air_condition: 'yes (luxury multi-zone)',
        age: 28,
        img1: './images/rangeRover/rangeRover_img1.jpg',
        img2: './images/rangeRover/rangeRover_img2.jpg',
        general: "The Range Rover Autobiography offers unmatched luxury, off-road capability, and sophisticated style, providing an elite driving experience both on and off the road."
    },
];
